// Code generated by entc, DO NOT EDIT.

package ent

import (
	"Coupon/ent/coupon"
	"Coupon/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CouponUpdate is the builder for updating Coupon entities.
type CouponUpdate struct {
	config
	hooks    []Hook
	mutation *CouponMutation
}

// Where appends a list predicates to the CouponUpdate builder.
func (cu *CouponUpdate) Where(ps ...predicate.Coupon) *CouponUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetCode sets the "Code" field.
func (cu *CouponUpdate) SetCode(s string) *CouponUpdate {
	cu.mutation.SetCode(s)
	return cu
}

// SetAmount sets the "Amount" field.
func (cu *CouponUpdate) SetAmount(f float64) *CouponUpdate {
	cu.mutation.ResetAmount()
	cu.mutation.SetAmount(f)
	return cu
}

// AddAmount adds f to the "Amount" field.
func (cu *CouponUpdate) AddAmount(f float64) *CouponUpdate {
	cu.mutation.AddAmount(f)
	return cu
}

// SetAlreadyUsed sets the "AlreadyUsed" field.
func (cu *CouponUpdate) SetAlreadyUsed(b bool) *CouponUpdate {
	cu.mutation.SetAlreadyUsed(b)
	return cu
}

// SetNillableAlreadyUsed sets the "AlreadyUsed" field if the given value is not nil.
func (cu *CouponUpdate) SetNillableAlreadyUsed(b *bool) *CouponUpdate {
	if b != nil {
		cu.SetAlreadyUsed(*b)
	}
	return cu
}

// SetExpireAt sets the "ExpireAt" field.
func (cu *CouponUpdate) SetExpireAt(i int64) *CouponUpdate {
	cu.mutation.ResetExpireAt()
	cu.mutation.SetExpireAt(i)
	return cu
}

// SetNillableExpireAt sets the "ExpireAt" field if the given value is not nil.
func (cu *CouponUpdate) SetNillableExpireAt(i *int64) *CouponUpdate {
	if i != nil {
		cu.SetExpireAt(*i)
	}
	return cu
}

// AddExpireAt adds i to the "ExpireAt" field.
func (cu *CouponUpdate) AddExpireAt(i int64) *CouponUpdate {
	cu.mutation.AddExpireAt(i)
	return cu
}

// Mutation returns the CouponMutation object of the builder.
func (cu *CouponUpdate) Mutation() *CouponMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CouponUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CouponMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CouponUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CouponUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CouponUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CouponUpdate) check() error {
	if v, ok := cu.mutation.Code(); ok {
		if err := coupon.CodeValidator(v); err != nil {
			return &ValidationError{Name: "Code", err: fmt.Errorf(`ent: validator failed for field "Coupon.Code": %w`, err)}
		}
	}
	return nil
}

func (cu *CouponUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   coupon.Table,
			Columns: coupon.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coupon.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coupon.FieldCode,
		})
	}
	if value, ok := cu.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: coupon.FieldAmount,
		})
	}
	if value, ok := cu.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: coupon.FieldAmount,
		})
	}
	if value, ok := cu.mutation.AlreadyUsed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: coupon.FieldAlreadyUsed,
		})
	}
	if value, ok := cu.mutation.ExpireAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: coupon.FieldExpireAt,
		})
	}
	if value, ok := cu.mutation.AddedExpireAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: coupon.FieldExpireAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coupon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// CouponUpdateOne is the builder for updating a single Coupon entity.
type CouponUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CouponMutation
}

// SetCode sets the "Code" field.
func (cuo *CouponUpdateOne) SetCode(s string) *CouponUpdateOne {
	cuo.mutation.SetCode(s)
	return cuo
}

// SetAmount sets the "Amount" field.
func (cuo *CouponUpdateOne) SetAmount(f float64) *CouponUpdateOne {
	cuo.mutation.ResetAmount()
	cuo.mutation.SetAmount(f)
	return cuo
}

// AddAmount adds f to the "Amount" field.
func (cuo *CouponUpdateOne) AddAmount(f float64) *CouponUpdateOne {
	cuo.mutation.AddAmount(f)
	return cuo
}

// SetAlreadyUsed sets the "AlreadyUsed" field.
func (cuo *CouponUpdateOne) SetAlreadyUsed(b bool) *CouponUpdateOne {
	cuo.mutation.SetAlreadyUsed(b)
	return cuo
}

// SetNillableAlreadyUsed sets the "AlreadyUsed" field if the given value is not nil.
func (cuo *CouponUpdateOne) SetNillableAlreadyUsed(b *bool) *CouponUpdateOne {
	if b != nil {
		cuo.SetAlreadyUsed(*b)
	}
	return cuo
}

// SetExpireAt sets the "ExpireAt" field.
func (cuo *CouponUpdateOne) SetExpireAt(i int64) *CouponUpdateOne {
	cuo.mutation.ResetExpireAt()
	cuo.mutation.SetExpireAt(i)
	return cuo
}

// SetNillableExpireAt sets the "ExpireAt" field if the given value is not nil.
func (cuo *CouponUpdateOne) SetNillableExpireAt(i *int64) *CouponUpdateOne {
	if i != nil {
		cuo.SetExpireAt(*i)
	}
	return cuo
}

// AddExpireAt adds i to the "ExpireAt" field.
func (cuo *CouponUpdateOne) AddExpireAt(i int64) *CouponUpdateOne {
	cuo.mutation.AddExpireAt(i)
	return cuo
}

// Mutation returns the CouponMutation object of the builder.
func (cuo *CouponUpdateOne) Mutation() *CouponMutation {
	return cuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CouponUpdateOne) Select(field string, fields ...string) *CouponUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Coupon entity.
func (cuo *CouponUpdateOne) Save(ctx context.Context) (*Coupon, error) {
	var (
		err  error
		node *Coupon
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CouponMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CouponUpdateOne) SaveX(ctx context.Context) *Coupon {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CouponUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CouponUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CouponUpdateOne) check() error {
	if v, ok := cuo.mutation.Code(); ok {
		if err := coupon.CodeValidator(v); err != nil {
			return &ValidationError{Name: "Code", err: fmt.Errorf(`ent: validator failed for field "Coupon.Code": %w`, err)}
		}
	}
	return nil
}

func (cuo *CouponUpdateOne) sqlSave(ctx context.Context) (_node *Coupon, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   coupon.Table,
			Columns: coupon.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coupon.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Coupon.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coupon.FieldID)
		for _, f := range fields {
			if !coupon.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coupon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Code(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coupon.FieldCode,
		})
	}
	if value, ok := cuo.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: coupon.FieldAmount,
		})
	}
	if value, ok := cuo.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: coupon.FieldAmount,
		})
	}
	if value, ok := cuo.mutation.AlreadyUsed(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: coupon.FieldAlreadyUsed,
		})
	}
	if value, ok := cuo.mutation.ExpireAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: coupon.FieldExpireAt,
		})
	}
	if value, ok := cuo.mutation.AddedExpireAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: coupon.FieldExpireAt,
		})
	}
	_node = &Coupon{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coupon.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
