// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"Coupon/external"
	"Coupon/handler"
	"Coupon/repository"
)

// Injectors from wire.go:

func DependencyProvider() (*handler.Coupon, error) {
	host, err := external.HostProvider()
	if err != nil {
		return nil, err
	}
	couponRepository, err := repository.CouponRepositoryProvider(host)
	if err != nil {
		return nil, err
	}
	coupon, err := handler.NewCouponProvider(couponRepository)
	if err != nil {
		return nil, err
	}
	return coupon, nil
}
